### ISSUE TITLE
Actions never came back for the satellite 'poller-master'. I reenable them for polling

### ISSUE THREAD

**Issue by moonrox** [naparuba/shinken#1482]
We have been using Shinken for quite a while. It is a single server configuration and recently we had a network outage.  We are running on a vm.
After the outage we started seeing issues with the poller/scheduler.
We changed all the Shinken .cfg files to use the IP of the server and not local host.

We are using Shinken 2.0.3 with thruk 1.84.
I have tried the redis-cli flushall options with both Shinken-scheduler stop/start and Shinken service stop/start.  

Here is the shinken event log message.

2015-01-29 13:45:30,408 [1422567930] Warning : 37 actions never came back for the satellite 'poller-master'. I reenable them for polling

Thruk shows the service as grey and they never actual run. They just get rescheduled.  Please advise if there is a way to fix this so that I don't have to rebuild from scratch.

John

**Comment by naparuba** [comment]
This was fixed in 2.2 version :)

**Comment by mpedeupe** [comment]
Hi naparuba,

After upgrading to 2.2, we found this issue was not resolved for us.  I am able to find the cause and have implemented a short term fix that has worked for us.  But I have not been able to find the actual root cause that is putting us in the bad situation.  Please see the details below and hopefully you can fix this at the root cause.

It appears that the cause of the problem is that the module_type for some checks is not set, instead of being set to fork.  We see the following error captured in the pollerd.log, but it is hiding the real issue.

    [1423516395] DEBUG: [Shinken] get_new_actions exception: <type 'exceptions.KeyError'>,u''
    [1423516395] INFO: [Shinken] [poller-master] Init connection with scheduler-master at http://localhost:7768/ (3s,120s)
    [1423516395] INFO: [Shinken] [poller-master] Connection OK with scheduler scheduler-master

This issue appears to be in satellite.py in the _got_queue_from_action function.

    def _got_queue_from_action(self, a):
            # get the module name, if not, take fork
            mod = getattr(a, 'module_type', 'fork')
            queues = self.q_by_mod[mod].items()

In the case of our checks that are failing to run, mod gets set to blank.  It does not pick up the default of 'fork' because the attribute does exist, it is just blank.

My simple fix that has worked for us is to set mod = 'fork' if it is blank.  I'm not sure if this could cause unexpected behavior elsewhere and I have not been able to find the code that should be setting the module_type upstream.

    def _got_queue_from_action(self, a):
        # get the module name, if not, take fork
        mod = getattr(a, 'module_type', 'fork')
        if mod == '':
            mod = 'fork'
        queues = self.q_by_mod[mod].items()

Please fix the root cause.  I look forward to being able to actually contribute to the code in the future, I just was not able to find what needed to be fixed this time.

Thanks for the great work!

Mike

**Comment by naparuba** [comment]
Can you provide me a configuration where I can reproduce your case? thanks :)

**Comment by Seb-Solon** [comment]
Closing because of no news. reopen in next version.
